### ISSUE TITLE
no handshake over IPv6

### ISSUE THREAD

**Issue by photogeen** [bigmoby/addon-wireguard-client#21]
I can only connect to my wireguard server when I enter a IPv4 address as an endpoint in the config of the wireguard-client add-on.
I tried it with domains pointing to my cable router (dual stack connection v4 and v6) or directly with IPv4 and IPv6 addresses.
The handshake only works with the v4 address.

When I use a dynamic domain wireguard-client resolves the domain into the v6 address. It looks like it's connected but there is no handshake entry in the log. And the transfer entry shows only sent, nothing received.

**LOG:**
```
interface: wg0
  public key: $key$
  private key: (hidden)
  listening port: 60973
peer: $some-key-here$
  preshared key: (hidden)
  endpoint: [some_ipv6_address]:51820
  allowed ips: 10.13.13.0/24
  transfer: 0 B received, 13.15 KiB sent
  persistent keepalive: every 25 seconds

```
**My config:**
```
interface:
  private_key: $mykey$
  address: 10.13.13.2
  dns:
    - 10.13.13.1
  post_up: iptables -t nat -A POSTROUTING -o wg0 -j MASQUERADE
  post_down: iptables -t nat -D POSTROUTING -o wg0 -j MASQUERADE
peers:
  - public_key: $pupkey$
    pre_shared_key: $pskey$
    endpoint: wg.example.com:51820
    allowed_ips:
      - 10.13.13.0/24
    persistent_keep_alive: "25"
```

**LOG (IPv4 address as endpoint instead of v6):**
```
interface: wg0
  public key: $$$$
  private key: (hidden)
  listening port: 54311
peer: $$$$
  preshared key: (hidden)
  endpoint: $ipv4_address$:51820
  allowed ips: 10.13.13.0/24
  latest handshake: 30 seconds ago
  transfer: 92 B received, 212 B sent
  persistent keepalive: every 25 seconds
```

When I connect to the same server from my iPhone (also from the same network as the homeassistantOS) the domain will always get resolved into a v4 address and everything is working.

What Do I miss here?

Thanks
Eugen
