### ISSUE TITLE
Extremely slow connection between server and client

### ISSUE THREAD

**Issue by gitrep3** [bigmoby/addon-wireguard-client#24]
# Problem/Motivation

My desired setup is that I have a public Wireguard VPN, eg. hosted on DigitalOcan, accessible by everyone.

Home Assistant, hosted locally, should connect to this Wireguard server, so the server can act as a reverse proxy and make my Home Assistant installation accessible from everywhere without any port forwarding issues.

I have the setup up and running with OpenVPN but want to switch, due to simpler configuration, to Wireguard.

This plugin manages to connect to my Wireguard server.
Connection is unusable slow. `curl` from Wireguard server to Homeassistant takes ages and usually ends with `Recv failure: Connection reset by peer`

## Expected behavior

Plugin connects to my Wireguard server.
Wireguard server can `curl` Home Assistant and get some HTML back

## Actual behavior

Plugin connects to my Wireguard server.

`curl` reponse takes ages and results in a "Recv failure: Connection reset by peer"
`curl`sees some header information sent by Home Assistant, so there is a connection, its just unusable slow:

```
root@3876e6bea848:/# curl 10.13.13.2:8123 -vvvv
*   Trying 10.13.13.2:8123...
* Connected to 10.13.13.2 (10.13.13.2) port 8123 (#0)
> GET / HTTP/1.1
> Host: 10.13.13.2:8123
> User-Agent: curl/7.87.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: text/html; charset=utf-8
< Content-Length: 9294
< Date: Sun, 12 Feb 2023 15:59:52 GMT
< Server: Python/3.10 aiohttp/3.8.1
< 
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

I also noticed when I `ping 10.13.13.2`it takes like 20 seconds until I get the first response. But once I got the first response the following reponses come up immediately
```
root@3876e6bea848:/# ping 10.13.13.2
PING 10.13.13.2 (10.13.13.2) 56(84) bytes of data.
64 bytes from 10.13.13.2: icmp_seq=19 ttl=64 time=18.6 ms
64 bytes from 10.13.13.2: icmp_seq=20 ttl=64 time=16.6 ms
64 bytes from 10.13.13.2: icmp_seq=21 ttl=64 time=22.8 ms
64 bytes from 10.13.13.2: icmp_seq=22 ttl=64 time=16.3 ms
^C
```

When I connect my phone to the Wireguard server it responds immediately to requests.

## Steps to reproduce

Wireguard server is set up like this:

```
version: '3'

networks:
  web:
    external: true

services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:1.0.20210914-alpine
    restart: unless-stopped
    networks:
      - default
      - web
    volumes:
      - /data/wireguard/config:/config
    cap_add:
      - NET_ADMIN
    environment:
      - SERVERURL=wireguard.mydomain.com
      - SERVERPORT=51820
      - PEERS=hass
      - INTERNAL_SUBNET=10.13.13.0
      - PERSISTENTKEEPALIVE_PEERS=
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      - traefik.enable=true
      - traefik.udp.services.wireguard-service.loadbalancer.server.port=51820
      - traefik.udp.routers.wireguard-router.entrypoints=wireguard
      - traefik.udp.routers.wireguard-router.service=wireguard-service
```

Wireguard client is set up like this:
```
Interface:

private_key: <redacted>
address: 10.13.13.2
dns:
  - 1.1.1.1
post_up: iptables -t nat -A POSTROUTING -o wg0 -j MASQUERADE
post_down: iptables -t nat -D POSTROUTING -o wg0 -j MASQUERADE


Peers:

- public_key: <redacted>
  pre_shared_key: <redacted>
  endpoint: wireguard.mydomain.com:51820
  allowed_ips:
    - 10.13.13.0/24
  persistent_keep_alive: 25
```
