### ISSUE TITLE
[TUN] [wg_server] No valid endpoint has been configured or discovered for peer 3

### ISSUE THREAD

**Issue by sunnyd24** [bigmoby/addon-wireguard-client#25]
# Problem/Motivation

> Cannot get a valid configuration that works with my wireguard server on windows

## Expected behavior

> To show Endpoint in Wireguard Server GUI, Tunnels tab under peer for HASSIO. Two other peers show valid endpoints which are mobile devices.

## Actual behavior

> Error message shown in Log tab of Wireguard Server GUI: 
[TUN] [wg_server] No valid endpoint has been configured or discovered for peer 3

## Steps to reproduce

>see below for yaml
```
interface:
  private_key: (***removed***)
  address: 10.147.17.51
  dns:
    - 8.8.8.8
    - 1.1.1.1
  post_up: >-
    iptables -t nat -A POSTROUTING -o wg0 -j MASQUERADE; iptables -A FORWARD -p
    tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
  post_down: >-
    iptables -t nat -D POSTROUTING -o wg0 -j MASQUERADE; iptables -D FORWARD -p
    tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
  mtu: 1420
peers:
  - public_key: (***removed***)
    pre_shared_key: (***removed***)
    endpoint: example.hostname.com:60000
    allowed_ips:
      - 10.147.17.0/24
    persistent_keep_alive: "25"
log_level: debug
```
Network ports tried: 80, 8080, 51820, 60000 all show {} in web browser.

I suspect it is an issue as the wireguard server is internally connected with an IP address 192.168.1.50 listening on port 60000, and the HASS is running on a Hyper-V VM  with an IP address 192.168.1.51.
