### ISSUE TITLE
"nc: bind: Address in use"

### ISSUE THREAD

**Issue by amber7212** [bigmoby/addon-wireguard-client#38]
# Problem/Motivation

Hi, 
I would like to use the addon between my server located at let's say 91.256.56.32:756 and the  HAclient located on a vps installation (docker)
I intend to join the server local network 192.168.0.0/24

Each time I launch the addon, I have a nc / bind error:

Here is the config:

interface:
  private_key: myprivate
  address: 192.168.27.65/32
  dns:
    - 8.8.8.8
  post_up: >-
    iptables -t nat -A POSTROUTING -o wg0 -j MASQUERADE; iptables -A FORWARD -p
    tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
  post_down: >-
    iptables -t nat -D POSTROUTING -o wg0 -j MASQUERADE; iptables -D FORWARD -p
    tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
  mtu: 1360
peers:
  - public_key: mypublic
    pre_shared_key: ""
    endpoint: 91.256.56.32:756
    allowed_ips:
      - 0.0.0.0/0
      - 192.168.0.0/24
      - 192.168.27.64/27
    persistent_keep_alive: "25"

Here is the log:

[10:47:17] INFO: Starting WireGuard Client...
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 192.168.27.65/32 dev wg0
[#] ip link set mtu 1360 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
nc: bind: Address in use
[#] ip -4 route add 192.168.27.64/27 dev wg0
[#] ip -4 route add 192.168.0.0/24 dev wg0
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] sysctl -q net.ipv4.conf.all.src_valid_mark=1
sysctl: error setting key 'net.ipv4.conf.all.src_valid_mark': Read-only file system
[#] resolvconf -d wg0 -f
[#] ip -4 rule delete table 51820
[#] ip -4 rule delete table main suppress_prefixlength 0
[#] ip link delete dev wg0
nc: bind: Address in use

What did I miss ? Any help, please ?

**Comment by bigmoby** [comment]
Hi @amber7212 ,
Assume you have the following configuration on the server side:

```
[Interface]
PrivateKey = 9s3b9qfH5Dcb8RlD5YzqX9Oi10ZzB4+ThOcUNxHQxGg=
Address = 10.0.0.1/24  # Server IP address in the WireGuard network
ListenPort = 51820

[Peer]
PublicKey = L9j5s8d5VxW5oF2n5+R2q3X1XyI+zN4/5gNnH8D6/l4=
PresharedKey = M1G7iU8z9Jxg7WzN5L5iU9b1K5gH7eU5hZ8uZ5G3m5I=
AllowedIPs = 10.0.0.2/32  # Client IP address in the WireGuard network
```

Then, on the client side (in the add-on), you should use a configuration similar to this:
```
interface:
  private_key: "A8Q7h3C5H4f3N2L8I3P7g1V8B6K1l7J9I4J8sH7P8eE="
  address: 10.0.0.2
  dns:
    - 8.8.8.8
    - 8.8.4.4
  post_up: >-
    iptables -t nat -A POSTROUTING -o wg0 -j MASQUERADE; iptables -A FORWARD -p
    tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
  post_down: >-
    iptables -t nat -D POSTROUTING -o wg0 -j MASQUERADE; iptables -D FORWARD -p
    tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
  mtu: 1420
peers:
  - public_key: "L9j5s8d5VxW5oF2n5+R2q3X1XyI+zN4/5gNnH8D6/l4="
    pre_shared_key: "M1G7iU8z9Jxg7WzN5L5iU9b1K5gH7eU5hZ8uZ5G3m5I="
    endpoint: [PUT SERVER MACHINE'S PUBLIC IP OR DOMAIN HERE]:51820
    allowed_ips:
      - 10.0.0.0/24
    persistent_keep_alive: "25"
```

I hope this could help you.
