### ISSUE TITLE
Read only filesystem causes issues while setting "sysctl -q net.ipv4.conf.all.src_valid_mark=1"

### ISSUE THREAD

**Issue by McFabi** [bigmoby/addon-wireguard-client#6]
# Problem/Motivation

Wireguard Client only connecting shortly. Then failing to. stay in the VPN. 

## Actual behavior

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: WireGuard Client
 Fast, modern, secure Wireguard tunnel (client)
-----------------------------------------------------------
 Add-on version: 0.1.5
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.13  (armv7 / raspberrypi4)
 Home Assistant Core: 2021.4.0
 Home Assistant Supervisor: 2021.03.9
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] config.sh: executing... 
[09:47:11] INFO: Ended to write Wireguard configuration into: [/etc/wireguard/wg0.conf]
[cont-init.d] config.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[09:47:11] INFO: Starting WireGuard Client...
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.7.0.4/24 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] sysctl -q net.ipv4.conf.all.src_valid_mark=1
sysctl: error setting key 'net.ipv4.conf.all.src_valid_mark': Read-only file system
[#] resolvconf -d wg0 -f
[#] ip -4 rule delete table 51820
[#] ip -4 rule delete table main suppress_prefixlength 0
[#] ip link delete dev wg0
[09:47:41] INFO: Requesting current status from WireGuard Client...
[09:48:11] INFO: Requesting current status from WireGuard Client...
```

## Steps to reproduce

Standard HomeAssistant OS install on RPI4

**Comment by bigmoby** [comment]
@McFabi please could you post here your add-on configuration? Please pay attentions to NOT share private information, please obfuscate these parts! And, if you could also the generated wireguard file (under /etc/wireguard/wg0.conf).
Cheers

**Comment by McFabi** [comment]
Thanks for your help:
My Add-on Config:
```
interface:
  private_key: key
  address: 10.7.0.4
  dns:
    - 8.8.8.8
    - 8.8.4.4
  post_up: iptables -t nat -A POSTROUTING -o wg0 -j MASQUERADE
  post_down: iptables -t nat -D POSTROUTING -o wg0 -j MASQUERADE
peer:
  public_key: key
  pre_shared_key: key
  endpoint: 'my_wireguard_server_ip:51820'
  allowed_ips:
    - 0.0.0.0/0
  persistent_keep_alive: '25'
log_level: trace
```



```
[Interface]
PrivateKey = key
Address = 10.7.0.4/24
DNS = 8.8.8.8,8.8.4.4
PostUp = iptables -t nat -A POSTROUTING -o wg0 -j MASQUERADE
PostDown = iptables -t nat -D POSTROUTING -o wg0 -j MASQUERADE

[Peer]
PublicKey = key
PreSharedKey = key
Endpoint = server:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
```


The configuration looks good. The file was in the docker container of the corresponding add-on. Is that where it should be?

What's a little bit strange for me: I have docker -it in the container and tried to set the "sysctl -q net.ipv4.conf.all.src_valid_mark=1" and the Read only filesystem error came.
