### ISSUE TITLE
Issues connecting to exsiting infrastructure (no PSK) 

### ISSUE THREAD

**Issue by Lawdie** [bigmoby/addon-wireguard-client#7]
# Problem/Motivation

I'm having issues getting my connection working, partly because I dont use PSK, I can see activity on the server of the connection however the reverse link fails. I notice I can't force the peer address to a /32 so I have a subnet mismatch (the addon automatically appends /24, manually appending /32 into the config errors with 10.9.0.7/32/24)

## Expected behavior

WG connects and am able to access HA from the WG address. 

## Actual behavior

Unable to access HA via WG, host unable to ping WG Server

## Steps to reproduce

Config im using:

```
interface:
  private_key: PRIVATEKEY
  address: 10.9.0.7
  dns:
    - 8.8.8.8
    - 8.8.4.4
  post_up: iptables -t nat -A POSTROUTING -o wg0 -j MASQUERADE ; ping -c 2 10.9.0.1
  post_down: iptables -t nat -D POSTROUTING -o wg0 -j MASQUERADE
peer:
  public_key: REMOTEPUBKEY
  pre_shared_key: REMOTEPUBKEY
  endpoint: 'SERVER'
  allowed_ips:
    - 10.9.0.0/24
  persistent_keep_alive: '120'
```

If I was to do this in pure WG config it would look like this 
```
[Interface]
PrivateKey = HAPRIVATEKEY
Address = 10.9.0.7/32
PostUp = ping -c 2 10.9.0.1


[Peer]
PublicKey = REMOTEPUBKEY
AllowedIPs = 10.9.0.0/24
Endpoint = SERVER

```

I have 10 devices already talking to this WG server so there isn't anything awol on the server side
